### ISSUE TITLE
GUI has changed for Security Center: Missmatch in the screenshots & steps.

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Azure-security-and-management#22]
In HOL Step by Steps: [Excercise 3, Task 2](https://github.com/Microsoft/MCW-Azure-security-and-management/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Azure%20security%20and%20management.md#task-2-explore-security-center) Explore Security Center
There is missmatch in screenshots, steps as GUI has changed.
Can someone please review and update.

**Comment by DawnmarieDesJardins** [comment]
Linking to update issue #20
