### ISSUE TITLE
Option for Install monitoring agent on your Virtual machines is missing in Azure portal under Security Center

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Azure-security-and-management#27]
[Exercise 3 Task 2 Step 6 ](https://github.com/Microsoft/MCW-Azure-security-and-management/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Azure%20security%20and%20management.md#task-2-explore-security-center) -> **Click the option for **Install monitoring agent on your Virtual machines.** On the next screen, click Install agents to turn on automatic provision of the monitoring agent.**
but didn't find this option  under **Security Center** in Azure portal.

Can you please look into this and fix this?

**Comment by zobayer098** [comment]
Looks like your azure subscription is upgraded to standard tier already. 

Here are my findings - At the beginning of this task, it is mentioned to upgrade the subscription to standard tier. For the subscription that is not upgraded to Standard Tier for Azure Security Center the lab instruction will work. If it is already in the standard tier then in General - Getting Started area it will mention **Install agent automatically  All set -  All of your Azure subscriptions have automatic agent installation enabled.**   and in this case this option will not be available in the portal.

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 
Hi there,
I wanted to check in real quick to see if this has solved the problem you were having.  If it has, we can close this issue out as resolved.
Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue, no response from field.  Option to re-open if needed.

**Comment by Abhishekpathania01** [comment]
@DawnmarieDesJardins 
Hi, I'll test it out and let you know the status. 
Thanks.
