### ISSUE TITLE
WDS trainer presentation - PPT 

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-security-and-management#5]
Slide 2 - Abstract on the ReadMe page does not match the abstract on the PPT slide.
Slide 11 - First bullet item has a period at the end of the sentence.  MS Style guide states no end punctuation on bulleted items unless there are multiple sentences. (except question marks and colons).
Slide 15 - Remove period at the end of the second bullet item.
Slide 16 - Three of the icons do not have alt-text.
Slide 26 - Last two sentences need periods at the end (They aren't bullet items so punctuation is needed). Lower case A in Alerts.  Last sentence, add a comma after diagnostics. Missing alt-text on image.
Slide 27 - Missing alt-text on image.
Slide 28 - Add a period at the end of the last sentence on the slide (not a bulleted item).
Slide 30 - Add either a period or a colon after "broken out by severity...
Slide 32 - Missing alt-text on right side image
Slide 35 - Remove punctuation on since sentence bullet lines.  Is there supposed to be 4 bulleted items?  It looks like Application Insights has many capabilities.... may be a different bullet point.
Slide 37 - the images you have in the PPT are different than the image used in the trainer guide

**Comment by jtuliani** [comment]
Done.
Regarding Slide 37: The first image has been copied to the trainer guide. The second image is already in the trainer guide. The trainer guide has one extra image, because there is more space in the trainer guide and that image would not fit on the slide (and is not worth an extra slide).
