### ISSUE TITLE
Before the Lab document

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-security-and-management#7]
Need to update to most current template - Document is missing title/updated date info, license information & TOC

Document name should be:  Before the HOL - Azure security and management

MS Style guide states bulleted or numbered items should not have ending punctuation unless there are multiple sentences (except question marks and colons).  I corrected on this document, it will be an expectation moving forward.

**Comment by jtuliani** [comment]
Addressed in june-2018-update branch
